apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - image: docker.io/ollama/ollama:latest
        imagePullPolicy: Always
        name: container
        ports:
        - containerPort: 11434
          protocol: TCP
        resources:
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /.ollama
          name: ollama-storage
      restartPolicy: Always
      volumes:
      - name: ollama-storage
        persistentVolumeClaim:
          claimName: ollama-storage
